title = "Snigdha OS Kernel Switcher Settings"
[kernels]
official = [
    {
        name = "linux",
        description = " The default and most commonly used Linux kernel package in Arch Linux. It provides a general-purpose kernel suitable for most users and is updated regularly with the latest stable kernel releases from upstream.",
        headers = "linux-headers"
    },
    {
        name = "linux-lts",
        description = "The Long-Term Support (LTS) kernel, providing extended support for a specific kernel version with a focus on stability. It does not receive feature updates but gets security and bug fixes.",
        headers = "linux-lts-headers" 
    },
    {
        name = "linux-zen",
        description = "A kernel optimized for desktop performance, featuring tweaks and enhancements aimed at improving responsiveness and reducing latency.",
        headers = "linux-zen-headers"
    },
    {
        name = "linux-hardened",
        description = "A security-focused kernel with additional patches and configurations to enhance system security. It emphasizes hardening techniques against vulnerabilities and exploits.",
        headers = "linux-hardened-headers"
    },
    {
        name = "linux-rt",
        description = "A real-time kernel with patches that prioritize low-latency and determinism, designed for use in applications requiring real-time performance (e.g., audio production, robotics).",
        headers = "linux-rt-headers"
    },
    {
        name = "linux-rt-lts",
        description = "A real-time kernel with patches that prioritize low-latency and determinism, designed for use in applications requiring real-time performance (e.g., audio production, robotics) with Long Term Support.",
        headers = "linux-rt-lts-headers"
    },
]

community = [
    {
        name = "linux-xanmod",
        description = "A kernel fork designed to offer more cutting-edge features and optimizations, particularly for gaming and desktop performance.",
        headers = "linux-xanmod-headers",
        repository = "chaotic-aur",
    },
    {
        name = "linux-xanmod-lts",
        description = "A kernel fork designed to offer more cutting-edge features and optimizations, particularly for gaming and desktop performance with Long Term Support",
        headers = "linux-xanmod-lts-headers",
        repository = "chaotic-aur",
    },
    {
        name = "linux-cachyos",
        description = "The Linux BORE + LTO + Cachy Sauce Kernel by CachyOS with other patches and improvements. kernel and modules",
        headers = "linux-cachyos-headers",
        repository = "chaotic-aur",
    },
    {
        name = "linux-clear",
        description = "Linux kernel with patches from Clear Linux which allow for higher performance. This package includes the kernel and compiled modules.",
        headers = "linux-clear-headers",
        repository = "chaotic-aur",
    },
    {
        name = "linux-lqx",
        description = "The Linux Liquorix kernel and modules.",
        headers = "linux-lqx-headers",
        repository = "chaotic-aur",
    },
    {
        name = "linux-nitrous",
        description = "Modified Linux kernel optimized for Skylake X and newer, compiled using clang.",
        headers = "linux-nitrous-headers",
        repository = "chaotic-aur",
    },
]